### ISSUE TITLE
Cloak.Ecto.Type does not conform to the Ecto.Type behavior

### ISSUE THREAD

**Issue by WilHall** [danielberkompas/cloak_ecto#12]
The `Cloak.Ecto.Type` module does not conform to the [`Ecto.Type` behavior](https://hexdocs.pm/ecto/Ecto.Type.html). For example, [`equal/3`](https://hexdocs.pm/ecto/Ecto.Type.html#equal?/3) is not implemented.

Because of this, following the [`cloak_ecto` usage instructions](https://github.com/danielberkompas/cloak_ecto#usage) results in a custom Ecto type which does not conform to the `Ecto.Type` behavior. This can result in `UndefinedFunctionError` instances when Ecto tries to use the custom type in a way that is not implemented:
```
** (UndefinedFunctionError) function Application.Encrypted.Binary.equal?/2 is undefined or private
```

I believe either `Cloak.Ecto.Type` should be updated to `use Ecto.Type` such that the default implementations can be used as fallbacks, or the usage instructions should be updated to let consumers of `use Cloak.Ecto.Binary` know that they either need to `use Ecto.Type` or define the missing methods.

**Comment by ellamosi** [comment]
This pull request is related to the issue: https://github.com/danielberkompas/cloak_ecto/pull/11

Unsure of what the best solution is. But as it is now things will not work as documented with Ecto 3.5.

**Comment by drewolson** [comment]
This should be fixed in https://github.com/danielberkompas/cloak_ecto/commit/2238af0359a79d145b9e60013afd8aba3478c3ac

**Comment by ellamosi** [comment]
Great! 👏
