### ISSUE TITLE
In multi-tenant setting

### ISSUE THREAD

**Issue by daya** [danielberkompas/cloak_ecto#15]
Is there any way to make cloak_ecto use a unique key for every tenant? 

The runtime configuration `Cloak.Ecto.HMAC.init/1` is very useful but can it be invoked per process?

**Comment by danielberkompas** [comment]
I'm not aware of any way to do this, because Ecto only passes the raw values to `Ecto.Type`s for encoding/decoding, with none of the other fields from the schema. (Such as tenant ID or a key to use)  If you need this, you'll probably have to do it in your application logic.
