### ISSUE TITLE
Decrypt for postgresql's native encrypt function?

### ISSUE THREAD

**Issue by Cifer-Y** [danielberkompas/cloak_ecto#28]
Now I have a legacy database, a column is encrypted by PGP_SYM_ENCRYPT.

I wonder if  I can use cloak_ecto to deal with that?

**Comment by danielberkompas** [comment]
I'm not familiar with Postges's native encryption. It may be possible to develop a custom cipher module that is capable of decrypting the ciphertext though. See the docs on Cloak.Cipher: https://hexdocs.pm/cloak/Cloak.Cipher.html
