### ISSUE TITLE
Trouble loading the Cloak.Ecto.PBKDF2 library

### ISSUE THREAD

**Issue by acrolink** [danielberkompas/cloak_ecto#30]
I am getting this error message at compile time:

`module Cloak.Ecto.PBKDF2 is not loaded and could not be found`

Using `Erlang/OTP 24 [erts-12.2]` and `{:pbkdf2, "~> 2.0", github: "miniclip/erlang-pbkdf2"}` in `mix.exs`.

How to solve this issue?

**Comment by danielberkompas** [comment]
@acrolink I would suggest the following:

- Remove your `_build` and `deps` directory. Fetch deps and recompile.
- Try pinning `pbkdf2` to the same commit this repo uses : `75ef2d829962349395c53b630e844a729e5d9c53`

I may soon drop the dependency on pbkdf2 for users of Erlang 24. See #31
